// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SummaryStats() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-white rounded-xl shadow-sm p-6\"><h2 class=\"text-lg font-semibold text-gray-900 mb-4\">Summary</h2><div class=\"space-y-4\"><div class=\"bg-gray-50 rounded-lg p-4\"><div class=\"text-sm text-gray-600 mb-1\">Savings Rate</div><div class=\"text-2xl font-bold text-gray-900\">60.7%</div></div><div class=\"bg-gray-50 rounded-lg p-4\"><div class=\"text-sm text-gray-600 mb-1\">Daily Allowance</div><div class=\"text-2xl font-bold text-gray-900\">£68.55</div></div></div><!-- Category Breakdown --><div class=\"mt-6\"><h3 class=\"text-xs font-semibold text-gray-500 uppercase tracking-wider mb-3\">By Category</h3><div class=\"space-y-3\"><div class=\"flex justify-between items-center py-2 border-b border-gray-100\"><div class=\"flex items-center gap-2\"><div class=\"w-2 h-2 rounded-full bg-blue-500\"></div><span class=\"text-sm text-gray-700\">Housing</span></div><span class=\"font-semibold text-gray-900\">£850</span></div><div class=\"flex justify-between items-center py-2 border-b border-gray-100\"><div class=\"flex items-center gap-2\"><div class=\"w-2 h-2 rounded-full bg-purple-500\"></div><span class=\"text-sm text-gray-700\">Utilities</span></div><span class=\"font-semibold text-gray-900\">£200</span></div><div class=\"flex justify-between items-center py-2 border-b border-gray-100\"><div class=\"flex items-center gap-2\"><div class=\"w-2 h-2 rounded-full bg-green-500\"></div><span class=\"text-sm text-gray-700\">Food</span></div><span class=\"font-semibold text-gray-900\">£75</span></div><div class=\"flex justify-between items-center py-2\"><div class=\"flex items-center gap-2\"><div class=\"w-2 h-2 rounded-full bg-gray-400\"></div><span class=\"text-sm text-gray-700\">Other</span></div><span class=\"font-semibold text-gray-900\">£250</span></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
